<a href="https://colab.research.google.com/github/Rajath-Upadhya/Machine-Learning/blob/main/00_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [ ]:
import torch
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

Create a random tensor with shape `(7, 7)`.

In [ ]:
# Creating a random tensor
import torch
Random_tensor = torch.rand(7,7)
Random_tensor

tensor([[0.7939, 0.7401, 0.4998, 0.0328, 0.8883, 0.5146, 0.5652],
        [0.8013, 0.8108, 0.1850, 0.8883, 0.8704, 0.9943, 0.9052],
        [0.5143, 0.7257, 0.3130, 0.5204, 0.9200, 0.6691, 0.2317],
        [0.8158, 0.2121, 0.3450, 0.8662, 0.4046, 0.2767, 0.8196],
        [0.3408, 0.3775, 0.4038, 0.6766, 0.0349, 0.8176, 0.0512],
        [0.7078, 0.1510, 0.7181, 0.2939, 0.6171, 0.1281, 0.2230],
        [0.7394, 0.6420, 0.4996, 0.8552, 0.8782, 0.4198, 0.5920]])

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)`.

In [ ]:
# Matrix multiplication
Random_tensor_2 = torch.rand(1,7)
torch.mm(Random_tensor, Random_tensor_2.T)

tensor([[2.4646],
        [2.9294],
        [2.1870],
        [2.3265],
        [1.2234],
        [2.0427],
        [2.8157]])

Set the random seed to 0 and do exercises 2 & 3 over again.

In [ ]:
# Random seed
randome_seed = 0
torch.manual_seed(randome_seed)
Random_tensor_3 = torch.rand(7,7)
torch.manual_seed(randome_seed)
Random_tensor_4 = torch.rand(1,7)
# Multiplication with random seed
torch.mm(Random_tensor_3, Random_tensor_4.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

 Hw to set it with `torch.manual_seed()` but is there a GPU equivalen

In [ ]:
# Setting random seed in GPU
random_seed_gpu = 1234
torch.cuda.manual_seed(random_seed_gpu)
Random_tensor_5 = torch.rand(2,3).to(device)
Random_tensor_5

tensor([[0.8964, 0.4556, 0.6323],
        [0.3489, 0.4017, 0.0223]], device='cuda:0')

Create two random tensors of shape (2, 3) and send them both to the GPU

In [ ]:
Random_tensor_5 = torch.rand(2,3).to(device)
Random_tensor_6 = torch.rand(2,3).to(device)
Random_tensor_6

tensor([[0.2823, 0.6816, 0.9152],
        [0.3971, 0.8742, 0.4194]], device='cuda:0')

Perform a matrix multiplication on the tensors

In [ ]:
# Multiplication in GPU
multiplication_on_gpu = torch.mm(Random_tensor_5, Random_tensor_6.T)
multiplication_on_gpu

tensor([[0.7225, 0.5414],
        [0.8896, 1.0439]], device='cuda:0')

Find the maximum and minimum values of the output

In [ ]:
# Finding maximum and minimum values
torch.max(multiplication_on_gpu), torch.min(multiplication_on_gpu)

(tensor(1.0439, device='cuda:0'), tensor(0.5414, device='cuda:0'))

Find the maximum and minimum index values of the output

In [ ]:
multiplication_on_gpu.argmax(), multiplication_on_gpu.argmin()

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
import torch
random_seed = 7
torch.manual_seed(random_seed)
random_tensor_1 = torch.rand(1,1,1,10)
print(f"Tensor: {random_tensor_1}")
print(f"Shape: {random_tensor_1.shape}")
print(f"Squeezed tensor: {random_tensor_1.squeeze()}")
print(f"Squeezed shape: {random_tensor_1.squeeze().shape}")


Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape: torch.Size([1, 1, 1, 10])
Squeezed tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Squeezed shape: torch.Size([10])
