<a href="https://colab.research.google.com/github/Rajath-Upadhya/Machine-Learning/blob/main/00_Fundatmentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Fundamentals of Pytorch



In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
 # Scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [ ]:
scalar.ndim

0

In [ ]:
# Converting tensor to Python int
scalar.item()

8

In [ ]:
# Vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
# Matrix
Matrix = torch.tensor([[1,2],
                      [3,4]])
Matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
Matrix[1]

tensor([3, 4])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9],
                      [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [ ]:
TENSOR.shape

torch.Size([1, 4, 3])

In [ ]:
TENSOR.ndim

3

# Random Tensor

In [ ]:
 # Create Random Tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0273, 0.0035, 0.4764, 0.1614],
        [0.3536, 0.6433, 0.1615, 0.8566],
        [0.0907, 0.2756, 0.8690, 0.3343]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224, 3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
### Zeros and ones
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
# Use range
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note:** Tensor datatypes is one of the 3 errors you'll run into with Pytorch and deep learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # Datatype ("e.g. float32 or float26 or float64")
                               device=None, # CPU or GPU
                               requires_grad=False) # Whether or not to track gradients with tensor operations

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Converting float32 to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# Does not run into error, generally 2 datatypes leads to error

Ten = float_16_tensor * float_32_tensor

In [ ]:
Ten.dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get dataype from a tensor, use: tensor.dtype
2. Tensors not right shape - to get shape, tensor.shape
3. Tensors not on the right device - to get device from a tensor, use: tensor.device

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5337, 0.7761, 0.5558, 0.7862],
        [0.5077, 0.3309, 0.9516, 0.2241],
        [0.4843, 0.1008, 0.9493, 0.1693]])

In [ ]:
# Find out details of the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5337, 0.7761, 0.5558, 0.7862],
        [0.5077, 0.3309, 0.9516, 0.2241],
        [0.4843, 0.1008, 0.9493, 0.1693]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Tensor operations



*   Addition
*   Subtraction
*   Multiplication (element-wise)
* Division
* Matrix multiplication




In [ ]:
# Create a tensor and add 100 to it
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

### Matrix Multiplication

Two ways of performing multiplication in neural networks and deep learning

1. Multiplcation
2. Matrix multiplication (dot product)

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplcation
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.28 ms, sys: 0 ns, total: 1.28 ms
Wall time: 1.25 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 66 µs, sys: 6 µs, total: 72 µs
Wall time: 75.8 µs


tensor(14)

Shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

# Error: Inner dimension do not match: (3,2) * (3,2)
# It needs to be: (3,2) * (2,3) leading to 3*3 matrix (Outer dimension)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# To fix, use transpose: .T

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
# The matrix multiplication
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
print(torch.mm(tensor_A, tensor_B.T))
print(f"Output shape: {torch.mm(tensor_A, tensor_B.T).shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum etc (Tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

torch.mean() function requires a tensor of float32 datatype to work

In [ ]:
# Find the mean:
torch.mean(x)

# Datatype error

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
# Fixing the datatype error

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Finding the positional min and max

x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [ ]:
x[0], x[9]

(tensor(0), tensor(90))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multuple tensors on top of each other (vstack), or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapper) in a certain way


In [ ]:
y = torch.arange(1, 10)
y, y.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add an extra dimension
y_reshaped = y.reshape(1, 9)
y_reshaped, y_reshaped.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
y_reshaped = y.reshape(9, 1)
y_reshaped, y_reshaped.shape


(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
y_reshaped = y.reshape(3, 3)
y_reshaped, y_reshaped.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view
z = y.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

### Changing z changes y because a view of a tensor shares the same memory as the original y

In [ ]:
z[:,0] = 5
z, y

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([y, y, y, y], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_stacked = torch.stack([y, y, y, y], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
x_vstacked = torch.vstack([y, y, y, y])
x_vstacked, x_vstacked.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([4, 9]))

In [ ]:
x_hstacked = torch.hstack([y, y, y, y])
x_hstacked, x_hstacked.shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6,
         7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([36]))

In [ ]:
s = y_reshaped.reshape(1,9)
s, s.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {s}")
print(f"Previous shape: {s.shape}")

# Remove extra dimensions from s
y_squeezed = s.squeeze()
print(f"\nNew tensor: {y_squeezed}")
print(f"New shape: {y_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to target tensor at a specific dim
print(f"Previous tensor: {y_squeezed}")
print(f"Previous shape: {y_squeezed.shape}")

# Add an extra dimension with unsqueeze
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # Color channels

# Permite the original rensor to rearrange the axis or dim order
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

x_permuted

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


tensor([[[0.9534, 0.1796, 0.7322,  ..., 0.6042, 0.4134, 0.9838],
         [0.6442, 0.9314, 0.1562,  ..., 0.5146, 0.1098, 0.0443],
         [0.1926, 0.1074, 0.0581,  ..., 0.3296, 0.3207, 0.9984],
         ...,
         [0.8302, 0.2041, 0.4456,  ..., 0.4282, 0.9516, 0.0282],
         [0.9942, 0.7008, 0.5880,  ..., 0.7256, 0.9289, 0.3597],
         [0.3382, 0.9688, 0.5715,  ..., 0.2375, 0.3298, 0.3420]],

        [[0.8162, 0.2103, 0.1220,  ..., 0.7291, 0.5625, 0.3390],
         [0.6932, 0.2617, 0.4486,  ..., 0.3566, 0.8474, 0.2813],
         [0.6444, 0.0202, 0.4240,  ..., 0.5967, 0.1988, 0.0511],
         ...,
         [0.8001, 0.6841, 0.5981,  ..., 0.7184, 0.1637, 0.8083],
         [0.3370, 0.0810, 0.9750,  ..., 0.3203, 0.2132, 0.7731],
         [0.6841, 0.4900, 0.5551,  ..., 0.2382, 0.9325, 0.4523]],

        [[0.5426, 0.4808, 0.2096,  ..., 0.5150, 0.7701, 0.4791],
         [0.7002, 0.6416, 0.8283,  ..., 0.3727, 0.5600, 0.7074],
         [0.9279, 0.2977, 0.7353,  ..., 0.9888, 0.1592, 0.

In [ ]:
x_original[0, 0, 0] = 7284
x_permuted = x_original.permute(2, 0, 1)
x_original[0,0,0], x_permuted[0, 0, 0]

(tensor(7284.), tensor(7284.))

## Indexing (selecting data from tensors)
Indexing with Pytorch is similar to indexing with numpy

In [ ]:
# Create a tensor
import torch
# x has 9 values, and reshapes to 1, 3, 3
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on middle bracket (dim = 1)
# x[0][0] or x[0, 0]
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Index on the most inner bracket (lasst dimension)
x[0][2][2]

tensor(9)

In [ ]:
# Can als use ":" to select all of a target dimesion
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but ony index 1 of 2nd dimension
x[:, :, 1]


tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index values of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

# Pytorch tensors and Numpy

* Data in numpy array to Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tenor to numpy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# From float64 to float32
tensor_float32 = torch.from_numpy(array).type(torch.float32)
tensor_float32.dtype

torch.float32

In [ ]:
# If we change the array, it does not change the tensor created from it.
# Example if we add 1 to array, the created tensor remains same.
# array and tensor do not share same memeory

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor
# DataType is carried from torch to NumPy

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, and check numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

- Taking random out of random

- Neural network learns: start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data -> repeat

* To reduce the randomness in neural networks and PyTorch, **random seed** concept used.

* https://docs.pytorch.org/docs/2.14/notes/randomness.html


In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2797, 0.2971, 0.5560, 0.1468],
        [0.1103, 0.8984, 0.1769, 0.0802],
        [0.3231, 0.0549, 0.0056, 0.4131]])
tensor([[0.7878, 0.2386, 0.7155, 0.2055],
        [0.4211, 0.4775, 0.6353, 0.1073],
        [0.6568, 0.6326, 0.4243, 0.3402]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Random but reproducible tensors
import torch

# Set the random seed
Random_seed = 10
torch.manual_seed(Random_seed)
random_tensor_C = torch.rand(3,4)

# If not set again, it won't have random_seed to tensor_D
torch.manual_seed(Random_seed)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])
tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running on GPUs

- Faster computations (CUDA + NVIDIA)

In [ ]:
!nvidia-smi

Mon Sep  7 14:55:40 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Check for GPU access with PyTorch

- https://docs.pytorch.org/docs/2.14/notes/cuda.html

- Best practice: Run on GPU if available, or use CPU

In [ ]:
# No setup required
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Device count
torch.cuda.device_count()

1

In [ ]:
# Tensors and models on the GPU for faster computations
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# Move tensor back to the CPU
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_CPU = tensor_on_gpu.cpu().numpy()
tensor_back_on_CPU

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')